#server:
#  port: 8002 #微服务端口号为8001
spring:
#  application:
#    name: service-security #服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dd?serverTimezone=CST&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true #？后面参数表示时区，非常重要
    username: root
    password: 123456
    jackson: #我们的时区是东八区，应该加8个小时，时区显示格式也需要改成我们想要的
      date-format: yyyy-MM-DD HH:mm:ss
      time-zone: GMT+8
#  redis: #redis配置
#    host: 127.0.0.1 #你的redis地址
#    port: 6379 #端口号
#    database: 0
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 1024 # 最大连接数
#        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
#        max-idle: 200 #最大空闲连接
#        min-idle: 5 #最小空闲连接
# MyBatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-handlers-package: com.caleb.security.entity.* # 搜索指定包别名

jwt:
  tokenHeader: Authorization #JWT存储的请求头，请求是这个就是token的key
  secret: ukc8BDbRigUDaY6pZFfWus2jZWLPHO #JWT加解密使用的密钥
  expiration: 10 #JWT有效时间（60*60*24）
#  expiration: 43200000 #1000*60*60*12 12小时有效时间
  tokenHead: Bearer #JWT负载中拿到的开头，token字符串，tokenHead是字符串的头，也就是以它开头

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql