server:
  port: 8001 #微服务端口号为8001
# 日志配置
logging:
  level:
    com.caleb: debug
    org.springframework: warn
    com.alibaba.nacos.client.naming: error
spring:
  application:
    name: service-blog #服务名
    profiles:
      active: dev #环境设置 dev表示构建阶段，test表示测试阶段，prod表示发布阶段
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  jackson: #我们的时区是东八区，应该加8个小时，时区显示格式也需要改成我们想要的
    date-format: yyyy-MM-DD HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 修改参数，解决springboot2.6.x与swagger2不兼容
  redis: #redis配置
    host: 127.0.0.1 #你的redis地址
    port: 6379 #端口号
    password: "123456"
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 1024 # 最大连接数
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 200 #最大空闲连接
        min-idle: 5 #最小空闲连接
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml #配置mapper xml文件的路径
jwt:
  tokenHeader: Authorization #JWT存储的请求头，请求是这个就是token的key
  secret: ukc8BDbRigUDaY6pZFfWus2jZWLPHO #JWT加解密使用的密钥
  expiration: 600000 #JWT有效时间（60*60*24）
#  expiration: 43200000 #1000*60*60*12 12小时有效时间
  tokenHead: Bearer #JWT负载中拿到的开头，token字符串，tokenHead是字符串的头，也就是以它开头

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

